import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalHeader from "@/components/conditionalHeader";
import ConditionalFooter from "@/components/Conditionalfooter";
import { CartProvider } from "@/context/cartcontext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <CartProvider>
          <Suspense>
            {/* <ConditionalHeader /> */}
          </Suspense>
          <main className="flex-grow">{children}</main>
          <Suspense>
            {/* <ConditionalFooter /> */}
          </Suspense>
        </CartProvider>
      </body>
    </html>
  );
}
